# Use to test langchain-postgres
version: "3"
name: langchain-postgres

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: langchain
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
    ports:
      - "6023:5432"
    command: |
      postgres -c log_statement=all
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql postgresql://langchain:langchain@localhost/langchain --command 'SELECT 1;' || exit 1",
        ]
      interval: 5s
      retries: 60
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgvector:
    # postgres with the pgvector extension
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: langchain
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
    ports:
      - "6024:5432"
    command: |
      postgres -c log_statement=all
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql postgresql://langchain:langchain@localhost/langchain --command 'SELECT 1;' || exit 1",
        ]
      interval: 5s
      retries: 60
    volumes:
      - postgres_data_pgvector:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_data_pgvector:
